# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
name: OCI / Python snapshot

on: # yamllint disable-line rule:truthy
  schedule:
  - cron: "0 */6 * * *"
  pull_request:
    paths:
    - .github/workflows/python.yaml
    - "images/python/*.yaml"
    - "images/python/**/*.yaml"
  push:
    branches:
    - "main"
    paths:
    - .github/workflows/python.yaml
    - "images/python/*.yaml"
    - "images/python/**/*.yaml"
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    permissions:
      actions: read
      attestations: write
      contents: read
      id-token: write
      packages: write
      security-events: write

    strategy:
      matrix:
        version: [latest]
        variant: [prod, dev]

    name: ${{ matrix.version }}${{ matrix.variant == 'dev' && '-dev' || '' }}
    uses: "./.github/workflows/release.yaml"
    with:
      repository: nlamirault/atoma/python
      config-dir: images/python
      tag: ${{ matrix.version }}${{ matrix.variant == 'dev' && '-dev' || '' }}
      target: ${{ matrix.variant }}
      vex-file: vex/python.openvex.json
    secrets: inherit
